name: Quality Check
on:
  push:
  pull_request:
    branches:
      - main
jobs:
  quality-check:
    runs-on: ubuntu-latest
    env:
      AUTH_SECRET: ${{ secrets.AUTH_SECRET }}
      AUTH_URL: ${{ secrets.AUTH_URL }}
      DISCORD_CLIENT_ID: ${{ secrets.DISCORD_CLIENT_ID }}
      DISCORD_CLIENT_SECRET: ${{ secrets.DISCORD_CLIENT_SECRET }}
      BOT_SECRET: ${{ secrets.BOT_SECRET }}
      BOT_URL: ${{ secrets.BOT_URL }}
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      DIRECT_URL: ${{ secrets.DIRECT_URL }}
      UPLOADTHING_TOKEN: ${{ secrets.UPLOADTHING_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint

      # - name: Unit Tests
      #   run: npm run test
